name: Build Docker Image

on:
  workflow_call:
    inputs:
      OWNER_LC:
        description: "repo owner name"
        type: string
        required: true
jobs:
  build-docker-image:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ inputs.OWNER_LC }}/rocknix-build:latest