name: Build device

on:
  workflow_call:
    inputs:
      PROJECT:
        description: "The project name"
        type: string
        required: true
      DEVICE:
        description: "The device name"
        type: string
        required: true
      OWNER_LC:
        description: "repo owner name"
        type: string
        required: true
      NIGHTLY:
        description: "build nightly version"
        type: string
        required: true
      OFFICIAL:
        description: "build official version"
        type: string
        required: true

jobs:
  build-arm:
    uses: ./.github/workflows/build-arm.yml
    with:
      PROJECT: ${{ inputs.PROJECT }}
      DEVICE: ${{ inputs.DEVICE }}
      OWNER_LC: ${{ inputs.OWNER_LC }}

  build-aarch64-toolchain:
    uses: ./.github/workflows/build-aarch64-toolchain.yml
    with:
      PROJECT: ${{ inputs.PROJECT }}
      DEVICE: ${{ inputs.DEVICE }}
      OWNER_LC: ${{ inputs.OWNER_LC }}

  build-aarch64:
    needs: build-aarch64-toolchain
    uses: ./.github/workflows/build-aarch64.yml
    with:
      PROJECT: ${{ inputs.PROJECT }}
      DEVICE: ${{ inputs.DEVICE }}
      OWNER_LC: ${{ inputs.OWNER_LC }}

  build-aarch64-mame-lr:
    needs: build-aarch64-toolchain
    uses: ./.github/workflows/build-aarch64-mame-lr.yml
    with:
      PROJECT: ${{ inputs.PROJECT }}
      DEVICE: ${{ inputs.DEVICE }}
      OWNER_LC: ${{ inputs.OWNER_LC }}

  build-aarch64-qt6:
    needs: build-aarch64
    uses: ./.github/workflows/build-aarch64-qt6.yml
    with:
      PROJECT: ${{ inputs.PROJECT }}
      DEVICE: ${{ inputs.DEVICE }}
      OWNER_LC: ${{ inputs.OWNER_LC }}

  build-aarch64-emu-libretro:
    needs:
      - build-aarch64
      - build-aarch64-mame-lr
      - build-aarch64-qt6
    if: ${{ always() && !cancelled() && !contains(needs.*.result, 'failure')  }}
    uses: ./.github/workflows/build-aarch64-emu-libretro.yml
    with:
      PROJECT: ${{ inputs.PROJECT }}
      DEVICE: ${{ inputs.DEVICE }}
      OWNER_LC: ${{ inputs.OWNER_LC }}

  build-aarch64-emu-standalone:
    needs:
      - build-aarch64
      - build-aarch64-qt6
    if: ${{ always() && !cancelled() && !contains(needs.*.result, 'failure')  }}
    uses: ./.github/workflows/build-aarch64-emu-standalone.yml
    with:
      PROJECT: ${{ inputs.PROJECT }}
      DEVICE: ${{ inputs.DEVICE }}
      OWNER_LC: ${{ inputs.OWNER_LC }}

  build-aarch64-image:
    needs:
      - build-aarch64-emu-libretro
      - build-aarch64-emu-standalone
      - build-arm
    if: ${{ always() && !cancelled() && !contains(needs.*.result, 'failure')  }}
    uses: ./.github/workflows/build-aarch64-image.yml
    secrets: inherit
    with:
      PROJECT: ${{ inputs.PROJECT }}
      DEVICE: ${{ inputs.DEVICE }}
      OWNER_LC: ${{ inputs.OWNER_LC }}
      NIGHTLY: ${{ inputs.NIGHTLY }}
      OFFICIAL: ${{ inputs.OFFICIAL }}

  purge-artifact:
    name: Artifacts cleanup
    needs: build-aarch64-image
    if: ${{ always() && !cancelled() && !contains(needs.*.result, 'failure')  }}
    runs-on: ubuntu-24.04
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            aarch64 (${{ inputs.DEVICE }})
            aarch64-toolchain (${{ inputs.DEVICE }})
            arm (${{ inputs.DEVICE }})
            emu-libretro (${{ inputs.DEVICE }})
            emu-standalone (${{ inputs.DEVICE }})
            mame-lr (${{ inputs.DEVICE }})
            qt6 (${{ inputs.DEVICE }})
